[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["currencyrate"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/ScheduledTask","Category/Integration"]
  name = "currencyrate"
  org = "choreodemo1210"
  version = "3.1.0"

